package com.ai.assistant.domain.model

/**
 * A plan of actions generated by the AI to fulfill the user's command.
 * Can be a single step (when the AI needs to see screen after each action)
 * or multiple steps (when the AI is confident about the sequence).
 */
data class ActionPlan(
    val reasoning: String,
    val actions: List<UiAction>,
    val requiresScreenRefresh: Boolean = true,
    val isComplete: Boolean = false,
    val errorMessage: String? = null
)
